# Generated by Django 2.0 on 2019-09-29 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_advancebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancebooking',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
