# Generated by Django 2.0 on 2019-09-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0003_advancebooking_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.CharField(max_length=10000)),
            ],
        ),
        migrations.RemoveField(
            model_name='advancebooking',
            name='customer_name',
        ),
        migrations.DeleteModel(
            name='AdvanceBooking',
        ),
    ]
