# Generated by Django 2.0 on 2019-09-29 11:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel_app', '0004_auto_20190929_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomments',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='blogcomments',
            name='email',
        ),
        migrations.RemoveField(
            model_name='blogcomments',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='blogcomments',
            name='lastname',
        ),
        migrations.AddField(
            model_name='blogcomments',
            name='customer_name',
            field=models.ForeignKey(default=1, on_delete=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
