# Generated by Django 2.0 on 2019-09-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0006_auto_20190929_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomments',
            name='item',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
