# Generated by Django 2.0 on 2019-09-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0007_blogcomments_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomments',
            name='customer_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
