# Generated by Django 2.0 on 2019-09-29 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0008_auto_20190929_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomments',
            name='item',
        ),
    ]
