# Generated by Django 2.0 on 2019-09-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0009_remove_blogcomments_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomments',
            name='customer_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
