# Generated by Django 2.2.6 on 2019-10-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0010_auto_20190929_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('customer_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('room_type', models.CharField(choices=[('S', 'Standard'), ('D', 'Delux'), ('SD', 'Super Delux'), ('PD', 'Premier Delux'), ('ES', 'Executive Suit'), ('JS', 'Junior Suit'), ('HS', 'Honeymoon Suit')], max_length=1)),
                ('number_room', models.IntegerField()),
                ('number_days', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='BlogComments',
        ),
    ]
