# Generated by Django 2.2.6 on 2019-10-05 10:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0012_auto_20191005_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='customer_id',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
