# Generated by Django 2.2.6 on 2019-10-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0013_auto_20191005_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='customer_id',
            field=models.IntegerField(),
        ),
    ]
